# https://ai.google.dev/gemini-api/docs/image-generation
# https://cloud.google.com/vertex-ai/generative-ai/docs/image/overview

import logging
import os
import asyncio
from PIL import Image
from typing import List, Optional
from google import genai
from google.genai import types
from google.genai.errors import ClientError
from tenacity import retry, stop_after_attempt
from interfaces.image_output import ImageOutput
from utils.retry import after_func
from utils.rate_limiter import RateLimiter


class ImageGeneratorNanobananaGoogleAPI:
    """Image generator supporting both Imagen (Nanobanana 2) and Gemini models.

    - **Imagen models** (``imagen-*``): Uses ``generate_images()`` API — higher
      quality, text-to-image only (no reference images).
    - **Gemini models** (``gemini-*``): Uses ``generate_content()`` with
      ``response_modalities=["IMAGE"]`` — supports reference images for
      image-to-image generation.

    When a Gemini model is configured, it is used for all requests (including
    those with reference images). When an Imagen model is configured, it is
    used for text-only requests, and requests with reference images fall back
    to the Gemini model automatically.
    """

    # Model used when reference images are provided but the primary model
    # is Imagen (which doesn't support reference images via generate_images).
    GEMINI_REF_MODEL = "gemini-2.0-flash-001"

    def __init__(
        self,
        api_key: str = "",
        project: str = "",
        location: str = "",
        model: str = "imagen-4.0-generate-preview-06-06",
        rate_limiter: Optional[RateLimiter] = None,
    ):
        self.model = model
        self.rate_limiter = rate_limiter
        self._is_imagen = model.startswith("imagen")

        # Prefer Vertex AI when project is provided; fall back to API key
        if project:
            client_kwargs = {
                "project": project,
                "location": location or "us-central1",
            }
            logging.info(
                "Image gen: using Vertex AI (project=%s, location=%s)",
                project, client_kwargs["location"],
            )
        else:
            env_project = os.environ.get("GOOGLE_CLOUD_PROJECT", "")
            env_location = os.environ.get("GOOGLE_CLOUD_LOCATION", "us-central1")
            env_key = os.environ.get("GOOGLE_API_KEY", "") or api_key

            if env_project:
                client_kwargs = {
                    "project": env_project,
                    "location": env_location,
                }
                logging.info(
                    "Image gen: using Vertex AI from env (project=%s, location=%s)",
                    env_project, env_location,
                )
            elif env_key:
                client_kwargs = {"api_key": env_key}
                logging.info("Image gen: using Google AI Studio API key")
            else:
                raise ValueError(
                    "No Vertex AI project or Google API key configured. "
                    "Set GOOGLE_CLOUD_PROJECT + GOOGLE_CLOUD_LOCATION for Vertex AI, "
                    "or GOOGLE_API_KEY for AI Studio."
                )

        self.client = genai.Client(**client_kwargs)
        logging.info(
            "Image gen: primary model=%s (%s API)",
            self.model,
            "Imagen" if self._is_imagen else "Gemini",
        )

    async def _generate_imagen(
        self,
        prompt: str,
        aspect_ratio: Optional[str] = "16:9",
    ) -> ImageOutput:
        """Generate an image using Imagen's generate_images() API."""
        logging.info(f"Calling {self.model} (Imagen) to generate image...")

        max_retries = 3
        retry_delay = 5

        for attempt in range(max_retries):
            try:
                response = await self.client.aio.models.generate_images(
                    model=self.model,
                    prompt=prompt,
                    config=types.GenerateImagesConfig(
                        number_of_images=1,
                        aspect_ratio=aspect_ratio,
                    ),
                )
                break
            except ClientError as e:
                if e.status_code == 429 and attempt < max_retries - 1:
                    wait_time = retry_delay * (2 ** attempt)
                    logging.warning(
                        f"Rate limit hit (429), retrying in {wait_time}s... "
                        f"(attempt {attempt + 1}/{max_retries})"
                    )
                    await asyncio.sleep(wait_time)
                else:
                    raise

        if not response.generated_images:
            raise ValueError("No image generated by Imagen")

        image = response.generated_images[0].image
        if image is None:
            raise ValueError("Imagen returned an empty image")

        pil_image = Image.open(image) if not isinstance(image, Image.Image) else image
        return ImageOutput(fmt="pil", ext="png", data=pil_image)

    async def _generate_gemini(
        self,
        prompt: str,
        reference_images: List,
        aspect_ratio: Optional[str] = "16:9",
        model: Optional[str] = None,
    ) -> ImageOutput:
        """Generate an image using Gemini's generate_content() API with IMAGE modality."""
        gen_model = model or self.model
        logging.info(f"Calling {gen_model} (Gemini) to generate image...")

        max_retries = 3
        retry_delay = 5

        for attempt in range(max_retries):
            try:
                response = await self.client.aio.models.generate_content(
                    model=gen_model,
                    contents=reference_images + [prompt],
                    config=types.GenerateContentConfig(
                        response_modalities=["IMAGE"],
                        image_config=types.ImageConfig(
                            aspect_ratio=aspect_ratio,
                        ),
                    ),
                )
                break
            except ClientError as e:
                if e.status_code == 429 and attempt < max_retries - 1:
                    wait_time = retry_delay * (2 ** attempt)
                    logging.warning(
                        f"Rate limit hit (429), retrying in {wait_time}s... "
                        f"(attempt {attempt + 1}/{max_retries})"
                    )
                    await asyncio.sleep(wait_time)
                else:
                    raise

        image = None
        text = ""
        for part in response.candidates[0].content.parts:
            if part.text is not None:
                text += part.text
            elif part.inline_data is not None:
                image = part.as_image()

        if image is None:
            logging.error(f"No image generated. The response text is: {text}")
            raise ValueError("No image generated")

        return ImageOutput(fmt="pil", ext="png", data=image)

    @retry(stop=stop_after_attempt(3), after=after_func)
    async def generate_single_image(
        self,
        prompt: str,
        reference_image_paths: List[str] = [],
        aspect_ratio: Optional[str] = "16:9",
        **kwargs,
    ) -> ImageOutput:
        """Generate a single image.

        - If the primary model is Imagen and no reference images are provided,
          uses the Imagen ``generate_images()`` API.
        - If reference images are provided with an Imagen primary model, falls
          back to Gemini for that request (Imagen doesn't support refs).
        - If the primary model is Gemini, always uses ``generate_content()``.
        """
        # Apply rate limiting if configured
        if self.rate_limiter:
            await self.rate_limiter.acquire()

        reference_images = [Image.open(path) for path in reference_image_paths]

        if self._is_imagen:
            if reference_images:
                # Imagen doesn't support reference images — fall back to Gemini
                logging.info(
                    "Reference images provided with Imagen model; "
                    f"falling back to {self.GEMINI_REF_MODEL} for this request"
                )
                return await self._generate_gemini(
                    prompt=prompt,
                    reference_images=reference_images,
                    aspect_ratio=aspect_ratio,
                    model=self.GEMINI_REF_MODEL,
                )
            else:
                return await self._generate_imagen(
                    prompt=prompt,
                    aspect_ratio=aspect_ratio,
                )
        else:
            # Gemini model — supports reference images natively
            return await self._generate_gemini(
                prompt=prompt,
                reference_images=reference_images,
                aspect_ratio=aspect_ratio,
            )
